version: '3'

services:
  echo:
    image: ealen/echo-server
    mac_address: "aa:aa:aa:aa:aa:a0"
    networks:
      main:
        ipv4_address: 192.168.255.2
    ports:
      - "8081:80"
  
  client:
    image: curlimages/curl
    mac_address: "aa:aa:aa:aa:aa:a1"
    # mac_address: "bb:bb:bb:bb:bb:bb"
    networks:
      main:
        ipv4_address: 192.168.255.3
    command: tail -f /dev/null
        
  
  interceptor:
    build: .
    mac_address: "aa:aa:aa:aa:aa:a2"
    environment:
      - TARGET=192.168.255.3
      - VICTIM=192.168.255.2
      - MAC_ADDRESS=aa:aa:aa:aa:aa:a2
      - IP_ADDRESS=192.168.255.4
      - BAD_WORDS=bad-words.txt
    networks:
      main:
        ipv4_address: 192.168.255.4
    volumes:
      - ./:/src/app:ro
    privileged: true
    cap_add:
      - NET_ADMIN
    command: python interceptor.py
  

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.255.0/24
          # gateway: 192.168.255.255
